services:
  ethercheck-backend:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./data:/app/data
    expose:
      - "8080"  # внутренний порт для Nginx
    restart: unless-stopped

  ethercheck-nginx:
    image: nginx:latest
    ports:
      - "5890:80"  # внешний порт
    volumes:
      - ./data:/app/data  # общая папка для /list
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - ethercheck-backend
    restart: unless-stopped
